#!/bin/bash

docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

# build isn't needed if we docker pull instead
docker build -t mehow/slime_volley_dev /vagrant/dev_env
if [ "$1" == "attach" ]; then
    docker run -p 80:80 -ti -v /vagrant:/srv/slime_volley --name slime_volley_dev mehow/slime_volley_dev
else
    docker run -p 80:80 -d -v /vagrant:/srv/slime_volley --name slime_volley_dev mehow/slime_volley_dev
fi
