#!/bin/bash

# build isn't needed if we docker pull instead
docker build -t mehow/slime_volley_dev /vagrant/dev_env
docker run -p 80:80 -d -v /vagrant:/srv/slime_volley --name slime_volley_dev mehow/slime_volley_dev
